name: Deploy Frontend to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Copie des fichiers (Code source)
    - name: Copy files via SSH
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "~/apps/frontend-tradingbot"

    # Lancement des commandes sur le serveur
    - name: Build and Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        command_timeout: 30m
        script: |
          cd ~/apps/frontend-tradingbot
          
          # 1. On arrête le conteneur actuel
          docker compose -f docker-compose.prod.yml down
          
          # 2. LA MODIFICATION CRUCIALE : Build avec --no-cache
          # Cela force Docker à re-télécharger Alpine et refaire les mises à jour de sécurité
          docker compose -f docker-compose.prod.yml build --no-cache
          
          # 3. On lance le nouveau conteneur tout neuf
          docker compose -f docker-compose.prod.yml up -d
          
          
          # 4. On nettoie les vieilles images qui prennent de la place
          docker system prune -f